# -*- coding: utf-8 -*-
"""PDS_OEP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIH0RWUxyl6g0SXEGjTcGn9glH1AKT6j

# Healthcare Data Analytics for Disease Risk Prediction

**Project Overview:** This project aims to predict the risk of Diabetes based on clinical measurements. We will perform data analysis, visualize patterns, train multiple machine learning models, and build a prediction system.

**Dataset:** Pima Indians Diabetes Database.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Set visual style
sns.set(style='whitegrid')
import warnings
warnings.filterwarnings('ignore')

"""## 1. Data Loading
We will load the dataset directly from a public URL.
"""

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
df = pd.read_csv(url, names=columns)

print("Dataset Head:")
display(df.head())
print("\nDataset Info:")
print(df.info())

"""## 2. Exploratory Data Analysis (EDA)
We will visualize the data to understand distributions and relationships.
"""

# 1. Histogram of all features
df.hist(figsize=(12, 10), bins=20)
plt.suptitle('Distribution of Features')
plt.show()

# 2. Heatmap for Correlation
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Feature Correlation Heatmap')
plt.show()

# 3. Boxplot to see BMI vs Outcome
plt.figure(figsize=(8, 6))
sns.boxplot(x='Outcome', y='BMI', data=df)
plt.title('BMI Distribution by Diabetes Outcome')
plt.show()

"""## 3. Data Preprocessing
We handle zeros that should be treated as missing values, split the data, and scale features.
"""

# Replace 0 with NaN for columns where 0 is physiologically impossible
cols_to_fix = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_to_fix] = df[cols_to_fix].replace(0, np.nan)

# Fill NaN with median values
df.fillna(df.median(), inplace=True)

# Split features and target
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split into Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize/Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data Preprocessing Complete.")

"""## 4. Model Training & Comparison
We train three different models and compare their accuracy.
"""

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(max_depth=5, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

results = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc
    print(f"{name} Accuracy: {acc:.2%}")

# Compare Models
plt.figure(figsize=(10, 5))
sns.barplot(x=list(results.keys()), y=list(results.values()))
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy Score')
plt.ylim(0, 1)
plt.show()

"""## 5. Prediction System
We build a function to predict risk based on manual input.
"""

def predict_diabetes_risk(input_data):
    # Convert input to scaled numpy array
    input_array = np.array(input_data).reshape(1, -1)
    scaled_input = scaler.transform(input_array)

    # Using Random Forest (usually the most robust)
    prediction = models['Random Forest'].predict(scaled_input)[0]
    probability = models['Random Forest'].predict_proba(scaled_input)[0][1]

    print(f"--- Result ---")
    if prediction == 1:
        risk = "High Risk (Diabetes Detected)"
    else:
        risk = "Low Risk (No Diabetes Detected)"

    print(f"Prediction: {risk}")
    print(f"Probability of Risk: {probability:.2%}")

# Example Input: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DPF, Age]
example_patient = [2, 120, 70, 20, 80, 25.5, 0.35, 30]
print("Testing with Example Input:", example_patient)
predict_diabetes_risk(example_patient)

"""## 6. Feature Importance
To make the model's decisions more transparent, we will extract and visualize which features the Random Forest model found most important for predicting diabetes.
"""

# Extract feature importances from the Random Forest model
importances = models['Random Forest'].feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Visualize Feature Importance
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df, palette='magma')
plt.title('Key Factors for Diabetes Prediction (Feature Importance)')
plt.xlabel('Importance Score')
plt.ylabel('Clinical Feature')
plt.show()

print("Top 3 Predictors:")
display(feature_importance_df.head(3))

"""## 7. Model Evaluation: Confusion Matrix
We will use a confusion matrix to visualize the performance of our Random Forest model, specifically looking at its ability to correctly identify both diabetic and non-diabetic cases.
"""

# Generate Confusion Matrix for Random Forest
rf_model = models['Random Forest']
y_pred_rf = rf_model.predict(X_test_scaled)
cm = confusion_matrix(y_test, y_pred_rf)

# Visualize the Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Diabetes', 'Diabetes'],
            yticklabels=['No Diabetes', 'Diabetes'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix: Random Forest Model')
plt.show()

# Print detailed classification report
print("Detailed Classification Report:")
print(classification_report(y_test, y_pred_rf))

"""## 8. Hyperparameter Tuning
We will use `GridSearchCV` to find the optimal parameters for our Random Forest model to improve its predictive performance.
"""

from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy']
}

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=RandomForestClassifier(random_state=42),
                           param_grid=param_grid,
                           cv=5, n_jobs=-1, verbose=1, scoring='accuracy')

# Fit the grid search to the data
print("Starting Hyperparameter Tuning...")
grid_search.fit(X_train_scaled, y_train)

# Extract the best model
best_rf_model = grid_search.best_estimator_

# Evaluate the tuned model
y_pred_tuned = best_rf_model.predict(X_test_scaled)
acc_tuned = accuracy_score(y_test, y_pred_tuned)

print(f"\nBest Parameters: {grid_search.best_params_}")
print(f"Tuned Random Forest Accuracy: {acc_tuned:.2%}")

# Update our models dictionary to use the tuned version for the prediction system
models['Random Forest Tuned'] = best_rf_model

"""## 9. Performance Comparison: Baseline vs. Tuned Model
We compare the performance metrics of the initial Random Forest model against the optimized version produced by GridSearchCV.
"""

from sklearn.metrics import precision_score, recall_score

# Calculate metrics for Original Random Forest
rf_original = models['Random Forest']
y_pred_orig = rf_original.predict(X_test_scaled)
acc_orig = accuracy_score(y_test, y_pred_orig)
prec_orig = precision_score(y_test, y_pred_orig)
rec_orig = recall_score(y_test, y_pred_orig)

# Calculate metrics for Tuned Random Forest
rf_tuned = models['Random Forest Tuned']
y_pred_tuned = rf_tuned.predict(X_test_scaled)
acc_tuned = accuracy_score(y_test, y_pred_tuned)
prec_tuned = precision_score(y_test, y_pred_tuned)
rec_tuned = recall_score(y_test, y_pred_tuned)

# Create Comparison DataFrame
comparison_data = {
    'Metric': ['Accuracy', 'Precision', 'Recall'] * 2,
    'Value': [acc_orig, prec_orig, rec_orig, acc_tuned, prec_tuned, rec_tuned],
    'Model': ['Original RF'] * 3 + ['Tuned RF'] * 3
}
comp_df = pd.DataFrame(comparison_data)

# Plotting
plt.figure(figsize=(10, 6))
sns.barplot(x='Metric', y='Value', hue='Model', data=comp_df, palette='viridis')
plt.title('Performance Comparison: Original vs. Tuned Random Forest')
plt.ylim(0, 1)
plt.legend(loc='lower right')
plt.show()

print("Summary of Improvements:")
display(comp_df.pivot(index='Metric', columns='Model', values='Value'))

"""## 10. Tuned Model Evaluation: Detailed Classification Report
We evaluate the optimized Random Forest model using a classification report to understand its precision, recall, and F1-score for both classes.
"""

from sklearn.metrics import classification_report

# Get predictions from the tuned model
best_rf = models['Random Forest Tuned']
y_pred_tuned = best_rf.predict(X_test_scaled)

# Generate and print the report
print("Classification Report: Tuned Random Forest")
print(classification_report(y_test, y_pred_tuned, target_names=['No Diabetes', 'Diabetes']))